In [1]:
import numpy as np
import pandas as pd

In [2]:
health = pd.read_csv('healthcare_dataset.csv', sep=',')
health

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

55500 rows * 15 columns

In [3]:
health = health.rename(columns = {
    'Name' : 'name',
    'Age' : 'age',
    'Gender' : 'gender',
    'Blood Type' : 'blood_type',
    'Medical Condition' : 'medical_condition', 
    'Date of Admission' : 'doa', 
    'Doctor' : 'dr', 
    'Hospital' : 'hospital', 
    'Insurance Provider' : 'insurer', 
    'Billing Amount' : 'bill', 
    'Room Number' : 'room', 
    'Admission Type' : 'admission_type', 
    'Discharge Date' : 'discharge', 
    'Medication' : 'medicine', 
    'Test Results' : 'test'
})

In [4]:
health['name'] = health['name'].str.title()

In [5]:
health

,name,age,gender,blood_type,medical_condition,doa,dr,hospital,insurer,bill,room,admission_type,discharge,medicine,test
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [6]:
health['doa'] = pd.to_datetime(health['doa'])
health['discharge'] = pd.to_datetime(health['discharge'])

In [7]:
health['discharge'] = health['discharge'].dt.strftime('%d-%m-%Y')

In [8]:
health

,name,age,gender,blood_type,medical_condition,doa,dr,hospital,insurer,bill,room,admission_type,discharge,medicine,test
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,02-02-2024,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,26-08-2019,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,07-10-2022,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,18-12-2020,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,09-10-2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,15-09-2020,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,01-02-2020,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,10-08-2020,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,31-05-2019,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,29-04-2024,Ibuprofen,Abnormal

### Q1 : Calculate total Billing Amount across all admissions.

In [9]:
health['bill'].sum()

np.float64(1417432043.3952546)

### Q2 : Calculate average Billing Amount per admission and median Billing Amount.

In [10]:
health['bill'].mean()

np.float64(25539.316097211795)

In [11]:
health['bill'].median()

np.float64(25538.069375965664)

### Q3 : Identify top 10 hospitals by total Billing Amount.

In [12]:
health.groupby('hospital')['bill'].sum().sort_values(ascending=False).head(10)

hospital
Johnson PLC    1.084203e+06
LLC Smith      1.030190e+06
Smith PLC      1.029424e+06
Ltd Smith      1.003366e+06
Smith Ltd      9.700359e+05
Johnson Inc    9.411175e+05
Group Smith    9.029758e+05
Inc Brown      8.907565e+05
LLC Johnson    8.164384e+05
Smith Group    8.066313e+05
Name: bill, dtype: float64

### Q4 : Identify top 10 hospitals by total number of admissions.

In [13]:
health['hospital'].value_counts().head(10)

hospital
LLC Smith      44
Ltd Smith      39
Johnson PLC    38
Smith Ltd      37
Smith PLC      36
Smith Group    36
Johnson Inc    35
Smith Inc      34
Group Smith    32
Smith LLC      32
Name: count, dtype: int64

### Q5 : Compare hospitals by revenue vs volume (which hospitals are high revenue but low volume and vice versa).

In [14]:
hospital_metrics = health.groupby("hospital").agg(
    admissions=("hospital", "size"),
    total_billing=("bill", "sum"),
    avg_billing=("bill", "mean")
).reset_index()

In [15]:
high_rev_low_vol = hospital_metrics[
    (hospital_metrics["total_billing"] >= hospital_metrics["total_billing"].quantile(0.90)) &
    (hospital_metrics["admissions"] <= hospital_metrics["admissions"].median())
].sort_values("total_billing", ascending=False)

In [16]:
high_vol_low_rev = hospital_metrics[
    (hospital_metrics["admissions"] >= hospital_metrics["admissions"].quantile(0.90)) &
    (hospital_metrics["total_billing"] <= hospital_metrics["total_billing"].median())
].sort_values("admissions", ascending=False)

In [17]:
high_vol_low_rev

                       hospital  admissions  total_billing   avg_billing
16899                  LLC Tate           4   29607.759037   7401.939759
10771              Group Moreno           4   17803.704206   4450.926051
10542               Group Dixon           4   20446.093574   5111.523394
23240                 PLC Carey           4   24032.008965   6008.002241
39112         and Sons Thompson           4   26374.797985   6593.699496
...                         ...         ...            ...           ...
39445  and Vega Jones, Bautista           2   10576.609187   5288.304594
39463  and Wade, Huffman Arnold           2    -457.093708   -228.546854
39466     and Wagner, Lee Klein           2    -612.729850   -306.364925
39473    and Walker Glenn, Long           2    7690.794991   3845.397496
241               Aguirre-Davis           2   29189.885562  14594.942781

[1448 rows x 4 columns]

### Q6 : Identify top 10 doctors by total Billing Amount.

In [18]:
health.groupby('dr')['bill'].sum().sort_values(ascending=False).head(10)

dr
Michael Smith      784501.843132
Robert Smith       634792.990831
John Smith         610109.604175
Robert Johnson     524193.003178
David Smith        473345.609187
William Johnson    469198.116030
John Johnson       466769.966463
James Smith        461817.900317
Michael Johnson    460819.038528
David Johnson      445605.542275
Name: bill, dtype: float64

### Q7 : Identify top 10 doctors by total number of patients/admissions.

In [19]:
health['dr'].value_counts().head(10)

dr
Michael Smith       27
John Smith          22
Robert Smith        22
James Smith         20
Michael Johnson     20
David Smith         19
Robert Johnson      19
Michael Williams    18
John Johnson        17
Matthew Smith       17
Name: count, dtype: int64

### Q8 : Calculate the billing contribution percentage of the top 10 hospitals to total billing.

In [20]:
top10_hospitals = health.groupby('hospital')['bill'].sum().nlargest(10).sum()
top10_hospitals

np.float64(9475137.823741874)

In [21]:
total_hospitals = health['bill'].sum()
total_hospitals

np.float64(1417432043.3952546)

In [22]:
billing_contri = (top10_hospitals / total_hospitals) * 100
billing_contri

np.float64(0.66847210544539)

### Q9 : Calculate mean and median Age overall and by Gender.

In [23]:
health['age'].agg(['mean','median'])

mean      51.539459
median    52.000000
Name: age, dtype: float64

In [24]:
health.groupby('gender')['age'].agg(['mean','median'])

             mean  median
gender
Female  51.578735    52.0
Male    51.500252    52.0

### Q10 : Create Age Groups (0–12, 13–19, 20–39, 40–59, 60+) and calculate admissions count per age group.

In [25]:
bins = [0, 12, 19, 39, 59, 150]
labels = ["0-12", "13-19", "20-39", "40-59", "60+"]

In [26]:
health["age_group"] = pd.cut(health['age'], bins=bins, labels = labels, right=True, include_lowest=True)

In [27]:
health['age_group'].value_counts(dropna=False)

age_group
60+      21148
40-59    16480
20-39    16179
13-19     1693
0-12         0
Name: count, dtype: int64

### Q11 : Calculate admissions count by Gender and billing share (%) by Gender.

In [28]:
health['gender'].value_counts()

gender
Male      27774
Female    27726
Name: count, dtype: int64

In [29]:
health.groupby('gender')['bill'].sum() / health['bill'].sum()

gender
Female    0.498224
Male      0.501776
Name: bill, dtype: float64

### Q12 : Calculate admissions count by Blood Type and average Billing Amount by Blood Type.

In [30]:
health['blood_type'].value_counts()

blood_type
A-     6969
A+     6956
AB+    6947
AB-    6945
B+     6945
B-     6944
O+     6917
O-     6877
Name: count, dtype: int64

In [31]:
health.groupby('blood_type')['bill'].mean()

blood_type
A+     25664.566404
A-     25595.024701
AB+    25361.458784
AB-    25694.933091
B+     25429.723237
B-     25524.424636
O+     25249.740696
O-     25795.657833
Name: bill, dtype: float64

### Q13 : Identify top medical conditions by number of admissions.

In [32]:
health['medical_condition'].value_counts().head()

medical_condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Name: count, dtype: int64

### Q14: Identify top medical conditions by total Billing Amount.

In [33]:
health.groupby('medical_condition')['bill'].sum().sort_values(ascending=False).head()

medical_condition
Diabetes        2.385397e+08
Obesity         2.382149e+08
Arthritis       2.373291e+08
Hypertension    2.357207e+08
Asthma          2.354598e+08
Name: bill, dtype: float64

### Q15 : Identify medical conditions that are low volume but high billing (high-value conditions).

In [34]:
cond_metrics = health.groupby("medical_condition").agg(
    admissions=("medical_condition", "size"),
    total_billing=("bill", "sum"),
    avg_billing=("bill", "mean")
).reset_index()

In [35]:
high_bill_low_vol = cond_metrics[
    (cond_metrics['avg_billing'] >= cond_metrics['avg_billing'].quantile(0.75)) &
    (cond_metrics['admissions'] <= cond_metrics['admissions'].quantile(0.25))
    ].sort_values('avg_billing', ascending=False)
high_bill_low_vol

Empty DataFrame
Columns: [medical_condition, admissions, total_billing, avg_billing]
Index: []

### Q16 : Identify medical conditions that are high volume but low billing (operations-heavy conditions).

In [36]:
high_vol_low_bill = cond_metrics[
    (cond_metrics['avg_billing'] <= cond_metrics['avg_billing'].quantile(0.25)) &
    (cond_metrics['admissions'] >= cond_metrics['admissions'].quantile(0.75))
    ].sort_values('admissions', ascending=False)
high_vol_low_bill

Empty DataFrame
Columns: [medical_condition, admissions, total_billing, avg_billing]
Index: []

### Q17 : Create Length of Stay (LOS) in days using Discharge Date minus Date of Admission.

In [37]:
health['doa'] = pd.to_datetime(health['doa'], format='%d-%m-%Y')

In [38]:
health['discharge'] = pd.to_datetime(health['discharge'], format='%d-%m-%Y')

In [39]:
health['los'] = (health['discharge'] - health['doa']).dt.days

In [40]:
health[['doa','discharge','los']]

             doa  discharge  los
0     2024-01-31 2024-02-02    2
1     2019-08-20 2019-08-26    6
2     2022-09-22 2022-10-07   15
3     2020-11-18 2020-12-18   30
4     2022-09-19 2022-10-09   20
...          ...        ...  ...
55495 2020-08-16 2020-09-15   30
55496 2020-01-23 2020-02-01    9
55497 2020-07-13 2020-08-10   28
55498 2019-05-25 2019-05-31    6
55499 2024-04-02 2024-04-29   27

[55500 rows x 3 columns]

### Q18 : Calculate average and median LOS overall.

In [41]:
health['los'].agg(['mean','median'])

mean      15.509009
median    15.000000
Name: los, dtype: float64

### Q19 : Calculate average LOS by hospital and list top 10 hospitals with the longest LOS.

In [42]:
health.groupby('hospital')['los'].mean()

hospital
Abbott Inc                        3.0
Abbott Ltd                       19.0
Abbott Moore and Williams,       25.0
Abbott and Thompson, Sullivan    26.0
Abbott, Peters and Hoffman       13.0
                                 ...
and Zimmerman Sons                2.0
and Zuniga Davis Carlson,        17.0
and Zuniga Francis Peterson,     10.0
and Zuniga Sons                  15.0
and Zuniga Thompson, Blake        1.0
Name: los, Length: 39876, dtype: float64

In [43]:
health.groupby('hospital')['los'].mean().sort_values(ascending=False).head(10)

hospital
Clark-Howard                  30.0
Clark-Palmer                  30.0
Clarke-Lawrence               30.0
and Williams Lopez Conrad,    30.0
Acosta Sons and               30.0
Acosta Willis, Martin and     30.0
Coffey Humphrey, and Cole     30.0
Cohen, and Bowers Conley      30.0
Clark Blair, and Miller       30.0
Cole Alvarez, Johnson and     30.0
Name: los, dtype: float64

### Q20 : Calculate average LOS by medical condition.

In [44]:
health.groupby('medical_condition')['los'].mean()

medical_condition
Arthritis       15.517404
Asthma          15.696570
Cancer          15.495827
Diabetes        15.422936
Hypertension    15.458626
Obesity         15.464305
Name: los, dtype: float64

### Q21 : Compare LOS by admission type (Emergency, Urgent, Elective).

In [45]:
health.groupby('admission_type')['los'].agg(['mean','median','count'])

                     mean  median  count
admission_type
Elective        15.525328    15.0  18655
Emergency       15.595052    16.0  18269
Urgent          15.408000    15.0  18576

### Q22 : Identify hospitals with unusually long LOS but low average billing (inefficiency risk)

In [46]:
hosp_eff = health.groupby("hospital").agg(
    avg_los=("los", "mean"),
    avg_billing=("bill", "mean"),
    admissions=("hospital", "size")
).reset_index()

In [47]:
high_los_low_bill = hosp_eff[
    (hosp_eff['avg_billing'] <= hosp_eff['avg_billing'].quantile(0.25)) &
    (hosp_eff['avg_los'] >= hosp_eff['avg_los'].quantile(0.75))
    ].sort_values('avg_los', ascending=False)
high_los_low_bill

                           hospital  avg_los   avg_billing  admissions
38753        and Smith Dyer Vargas,     30.0   2616.849143           1
37                  Acosta Sons and     30.0   5808.691685           1
39866     and Zhang Heath, Stafford     30.0   4723.486346           1
39591       and Weeks, Green Jordan     30.0   9704.071353           1
39585        and Weber Miles, Nixon     30.0  12150.390146           1
...                             ...      ...           ...         ...
26787  Rodriguez, Herrera and Huynh     22.0    854.512308           1
26791   Rodriguez, Reid Hawkins and     22.0   6414.854181           1
26891           Rodriguez-Rodriguez     22.0   6492.831129           1
26910             Rodriguez-Wiggins     22.0   2599.705072           1
9937        Graham Wilson, and King     22.0  11998.658009           1

[2935 rows x 4 columns]

### Q23 : Identify hospitals with short LOS but high average billing (efficient/high-value pattern).

In [48]:
high_los_low_bill = hosp_eff[
    (hosp_eff['avg_billing'] >= hosp_eff['avg_billing'].quantile(0.25)) &
    (hosp_eff['avg_los'] <= hosp_eff['avg_los'].quantile(0.75))
    ].sort_values('avg_billing', ascending=False)
high_los_low_bill

                          hospital  avg_los   avg_billing  admissions
12427             Hernandez-Morton     14.0  52373.032374           2
32412                Walker-Garcia      2.0  52170.036854           2
9288               George-Gonzalez      9.0  52102.240889           1
26661                 Rocha-Carter      2.0  52092.669896           1
4897                Clark-Espinoza      8.0  51848.201597           1
...                            ...      ...           ...         ...
17433                    Lee-White      1.0  14108.662398           1
1407   Barnes Anderson, Martin and     10.0  14107.573519           1
7459                  Esparza-Holt      9.0  14106.039841           1
29073    Smith, Santiago Lewis and     10.0  14105.125910           1
7024                Dudley-Schmidt     13.0  14103.922535           1

[22595 rows x 4 columns]

### Q24 : Calculate admissions count by Insurance Provider.

In [49]:
health['insurer'].value_counts()

insurer
Cigna               11249
Medicare            11154
UnitedHealthcare    11125
Blue Cross          11059
Aetna               10913
Name: count, dtype: int64

### Q25 : Calculate total Billing Amount by Insurance Provider.

In [50]:
health.groupby('insurer')['bill'].sum()

insurer
Aetna               2.788631e+08
Blue Cross          2.832543e+08
Cigna               2.871393e+08
Medicare            2.857208e+08
UnitedHealthcare    2.824545e+08
Name: bill, dtype: float64

### Q26 : Calculate average Billing Amount per admission by Insurance Provider.

In [51]:
health.groupby('insurer')['bill'].mean()

insurer
Aetna               25553.294506
Blue Cross          25613.011503
Cigna               25525.766314
Medicare            25615.990508
UnitedHealthcare    25389.172390
Name: bill, dtype: float64

### Q27 : Identify insurance providers that bring high volume but low value and low volume but high value.

In [52]:
ins_eff = health.groupby("insurer").agg(
    total_billing = ('bill', 'sum'),
    avg_billing=("bill", "mean"),
    admissions=("insurer", "size")
).reset_index()

In [53]:
high_vol_low_value = ins_eff[
    (ins_eff['avg_billing'] <= ins_eff['avg_billing'].quantile(0.25)) &
    (ins_eff['admissions'] >= ins_eff['admissions'].quantile(0.75))
    ].sort_values('admissions', ascending=False)
high_vol_low_value

  insurer  total_billing   avg_billing  admissions
2   Cigna   2.871393e+08  25525.766314       11249

In [54]:
high_value_low_vol = ins_eff[
    (ins_eff['avg_billing'] >= ins_eff['avg_billing'].quantile(0.75)) &
    (ins_eff['admissions'] <= ins_eff['admissions'].quantile(0.25))
    ].sort_values('avg_billing', ascending=False)
high_value_low_vol

      insurer  total_billing   avg_billing  admissions
1  Blue Cross   2.832543e+08  25613.011503       11059

### Q28 : Compare admission types across insurance providers (payer mix patterns).

In [55]:
pd.crosstab(health["insurer"], health["admission_type"], normalize="index") * 100

admission_type     Elective  Emergency     Urgent
insurer
Aetna             34.399340  33.675433  31.925227
Blue Cross        33.881906  32.814902  33.303192
Cigna             32.971820  32.687350  34.340830
Medicare          32.983683  32.947821  34.068496
UnitedHealthcare  33.851685  32.476404  33.671910

### Q29 : Identify hospitals that depend heavily on a single insurance provider (concentration risk).

In [56]:
hosp_ins = pd.crosstab(health['hospital'], health['insurer'])

In [57]:
share = hosp_ins.div(hosp_ins.sum(axis=1), axis=0)

In [58]:
share['max'] = share.max(axis=1)

In [59]:
highly_dependent = share[share['max'] >= 0.70].sort_values('max', ascending=False)
highly_dependent.head(10)

insurer,Aetna,Blue Cross,Cigna,Medicare,UnitedHealthcare,max
hospital,,,,,,
"and Zuniga Thompson, Blake",0.0,0.0,0.0,0.0,1.0,1.0
Abbott Inc,0.0,0.0,0.0,1.0,0.0,1.0
Abbott Ltd,0.0,0.0,0.0,0.0,1.0,1.0
"Abbott Moore and Williams,",0.0,0.0,0.0,0.0,1.0,1.0
"Abbott and Thompson, Sullivan",0.0,1.0,0.0,0.0,0.0,1.0
"Abbott, Peters and Hoffman",0.0,0.0,0.0,1.0,0.0,1.0
"Abbott, Vazquez Bautista and",1.0,0.0,0.0,0.0,0.0,1.0
Abbott-Castillo,0.0,0.0,0.0,0.0,1.0,1.0
Abbott-Coleman,0.0,0.0,1.0,0.0,0.0,1.0
Abbott-Ferrell,0.0,1.0,0.0,0.0,0.0,1.0

### Q30 : Calculate admissions count by Admission Type and billing contribution (%) by Admission Type.

In [60]:
health['admission_type'].value_counts()

admission_type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64

In [61]:
bill_share = (health.groupby('admission_type')['bill'].sum() / health['bill'].sum()) * 100
bill_share

admission_type
Elective     33.695410
Emergency    32.863089
Urgent       33.441502
Name: bill, dtype: float64

### Q31 : Compare average Billing Amount by Admission Type.

In [62]:
health.groupby('admission_type')['bill'].mean()

admission_type
Elective     25602.226311
Emergency    25497.397157
Urgent       25517.364497
Name: bill, dtype: float64

### Q32 : Compare average LOS by Admission Type.

In [63]:
health.groupby('admission_type')['los'].mean()

admission_type
Elective     15.525328
Emergency    15.595052
Urgent       15.408000
Name: los, dtype: float64

### Q33 : Identify hospitals with unusually high emergency admission percentage.

In [64]:
high_emergency = (pd.crosstab(health['hospital'], health['admission_type'], normalize='index') * 100)

emergency_col = None
for c in high_emergency.columns:
    if str(c).strip().lower() == "emergency":
        emergency_col = c
        break

if emergency_col is None:
    high_emergency
else:
    high_emergency[[emergency_col]].sort_values(emergency_col, ascending=False).head(15)

### Q34 : Identify medical conditions most associated with Emergency admissions.

In [65]:
if emergency_col is None:
    emergency_conditions = None
else:
    emergency_conditions = (health[health["admission_type"] == emergency_col]["medical_condition"]
                            .value_counts()
                            .head(15))
emergency_conditions

medical_condition
Obesity         3126
Arthritis       3108
Diabetes        3017
Cancer          3015
Asthma          3002
Hypertension    3001
Name: count, dtype: int64

### Q35 : Identify top medications by frequency (most prescribed).

In [66]:
health['medicine'].value_counts()

medicine
Lipitor        11140
Ibuprofen      11127
Aspirin        11094
Paracetamol    11071
Penicillin     11068
Name: count, dtype: int64

### Q36 : Calculate average Billing Amount by medication to identify high-cost medication patterns.

In [67]:
health.groupby('medicine')['bill'].mean()

medicine
Aspirin        25594.255074
Ibuprofen      25735.575732
Lipitor        25342.468884
Paracetamol    25533.470236
Penicillin     25490.917427
Name: bill, dtype: float64

### Q37 : Find the most common medication used for each medical condition.

In [68]:
pd.crosstab(health['medicine'], health['medical_condition'], normalize='index')

medical_condition,Arthritis,Asthma,Cancer,Diabetes,Hypertension,Obesity
medicine,,,,,,
Aspirin,0.172886,0.162430,0.160988,0.167478,0.168109,0.168109
Ibuprofen,0.163746,0.164195,0.168329,0.167251,0.170127,0.166352
Lipitor,0.163824,0.163645,0.172531,0.169928,0.165889,0.164183
Paracetamol,0.169542,0.170536,0.167374,0.163581,0.167013,0.161955
Penicillin,0.168594,0.166697,0.161999,0.169949,0.161728,0.171034

In [69]:
med_by_condition = (health.groupby(["medical_condition", "medicine"])
                                .size()
                                .reset_index(name="count")
                                .sort_values(["medical_condition", "count"], ascending=[True, False])
                                .groupby("medical_condition")
                                .head(1)
                                .reset_index(drop=True))
med_by_condition

  medical_condition     medicine  count
0         Arthritis      Aspirin   1918
1            Asthma  Paracetamol   1888
2            Cancer      Lipitor   1922
3          Diabetes      Lipitor   1893
4      Hypertension    Ibuprofen   1893
5           Obesity   Penicillin   1893

### Q38 : Check doctor-level variation in medication prescribing (do some doctors prescribe certain medications disproportionately).

In [70]:
doc_med = pd.crosstab(health['dr'], health['medicine'])

In [71]:
share = doc_med.div(doc_med.sum(axis=1), axis=0)

In [72]:
share['max'] = share.max(axis=1)

In [73]:
share[share['max'] >= 0.50].sort_values('max', ascending=False).head(10)

medicine          Aspirin  Ibuprofen  Lipitor  Paracetamol  Penicillin  max
dr
Zachary Walter        0.0        0.0      1.0          0.0         0.0  1.0
Zachary Walker        0.0        0.0      0.0          0.0         1.0  1.0
Zachary Thompson      0.0        0.0      0.0          0.0         1.0  1.0
Zachary Terry         1.0        0.0      0.0          0.0         0.0  1.0
Zachary Swanson       0.0        1.0      0.0          0.0         0.0  1.0
Zachary Sutton        0.0        1.0      0.0          0.0         0.0  1.0
Zachary Sullivan      1.0        0.0      0.0          0.0         0.0  1.0
Zachary Stewart       0.0        1.0      0.0          0.0         0.0  1.0
Zachary Stein         1.0        0.0      0.0          0.0         0.0  1.0
Zachary Stanley       0.0        0.0      0.0          0.0         1.0  1.0

### Q39 : Calculate distribution of Test Results (Normal, Abnormal, Inconclusive).

In [74]:
health['test'].value_counts()

test
Abnormal        18627
Normal          18517
Inconclusive    18356
Name: count, dtype: int64

### Q40 : Calculate test result distribution by medical condition.

In [75]:
pd.crosstab(health['test'], health['medical_condition'], normalize='index') * 100

medical_condition,Arthritis,Asthma,Cancer,Diabetes,Hypertension,Obesity
test,,,,,,
Abnormal,17.114941,16.153970,16.739142,17.007570,16.170076,16.814302
Inconclusive,16.822837,16.501416,16.670299,16.594029,16.839181,16.572238
Normal,16.374143,16.995194,16.465950,16.687368,16.968191,16.509154

### Q41 : Compare Billing Amount across test results (do abnormal results have higher billing).

In [76]:
health.groupby('test')['bill'].agg(['mean','median','count']).sort_values('mean', ascending=False)

                      mean        median  count
test
Inconclusive  25623.686846  25682.830526  18356
Abnormal      25538.353552  25565.637641  18627
Normal        25456.647191  25361.950104  18517

### Q42 : Compare LOS across test results.

In [77]:
los= health.groupby('test')['los'].agg(['mean','median','count']).sort_values('mean', ascending=False)
los

                   mean  median  count
test
Normal        15.547875    16.0  18517
Abnormal      15.509475    15.0  18627
Inconclusive  15.469329    15.0  18356

### Q43 : Calculate monthly admissions trend (admissions count per month)

In [78]:
health["month"] = health["doa"].dt.to_period("M").astype(str)
health['month'].value_counts().sort_index()

month
2019-05     686
2019-06     907
2019-07     957
2019-08    1001
2019-09     936
           ...
2024-01     909
2024-02     880
2024-03     906
2024-04     946
2024-05     213
Name: count, Length: 61, dtype: int64

### Q44 : Calculate monthly total billing trend (total billing per month).

In [79]:
health.groupby('month')['bill'].sum().sort_index()

month
2019-05    1.765315e+07
2019-06    2.388518e+07
2019-07    2.477156e+07
2019-08    2.539796e+07
2019-09    2.333408e+07
               ...
2024-01    2.343743e+07
2024-02    2.253791e+07
2024-03    2.289216e+07
2024-04    2.351686e+07
2024-05    5.431298e+06
Name: bill, Length: 61, dtype: float64

### Q45 : Identify peak months for emergency admissions.

In [80]:
if emergency_col is None:
    peak_emergency_months = None
else:
    peak_emergency_months = (health[health["admission_type"] == emergency_col]
                             .groupby("month")
                             .size()
                             .sort_values(ascending=False)
                             .head(10))
peak_emergency_months

month
2020-05    358
2020-07    357
2020-08    336
2020-01    333
2024-04    332
2023-03    325
2020-12    325
2022-08    322
2021-03    320
2023-05    320
dtype: int64

### Q46 : Check whether specific medical conditions show seasonality (spikes in certain months).

In [81]:
condition_monthly = (health.groupby(["medical_condition", "month"]).size()
                     .reset_index(name="admissions")
                     .sort_values(["medical_condition", "month"]))
condition_monthly

    medical_condition    month  admissions
0           Arthritis  2019-05         114
1           Arthritis  2019-06         139
2           Arthritis  2019-07         147
3           Arthritis  2019-08         200
4           Arthritis  2019-09         147
..                ...      ...         ...
361           Obesity  2024-01         145
362           Obesity  2024-02         140
363           Obesity  2024-03         134
364           Obesity  2024-04         155
365           Obesity  2024-05          30

[366 rows x 3 columns]

In [82]:
health.to_csv('healthcare.csv')